In [ ]:
# Создаем выбор input (марка / основная марка) в зависимости от того, что ввел пользователь

In [6]:
import pandas as pd

df = pd.read_csv('/home/ranil/Рабочий стол/PROJECT/ml/data/preprocessing_result.csv', index_col= 0)
df.head()

/tmp/ipykernel_21858/2537223579.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/ranil/Рабочий стол/PROJECT/ml/data/preprocessing_result.csv', index_col= 0)

,Наименование,ГОСТ,Телефон,Тип_продукции,Размер_A,Типоразмер,Марка,Примечание_для_размера,Толщина,Диапазон_min,...,Тип_материала,Основная_марка,Свариваемость,Тип_стандарта,Номер_стандарта,Год_стандарта,Категория_цены,Звоните,Цена,Условие_цены
0,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,ст3,0,не указан,NaN,0,р./т,False,47500.0,NaN
1,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Не указан,не указан,0,не указан,NaN,0,р./т,False,48500.0,NaN
2,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,а240,0,не указан,NaN,0,р./т,False,69000.0,NaN
3,Арматура А1,NaN,NaN,Число,8.0,NaN,NaN,NaN,NaN,NaN,...,Не указан,не указан,0,не указан,NaN,0,р./т,False,50900.0,NaN
4,Арматура А1,NaN,NaN,Число,8.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,а240,0,не указан,NaN,0,р./т,False,69000.0,NaN

In [4]:
df

,Наименование,ГОСТ,Телефон,Тип_продукции,Размер_A,Типоразмер,Марка,Примечание_для_размера,Толщина,Диапазон_min,...,Тип_материала,Основная_марка,Свариваемость,Тип_стандарта,Номер_стандарта,Год_стандарта,Категория_цены,Звоните,Цена,Условие_цены
0,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,ст3,0,не указан,NaN,0,р./т,False,47500.0,NaN
1,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Не указан,не указан,0,не указан,NaN,0,р./т,False,48500.0,NaN
2,Арматура А1,NaN,NaN,Число,10.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,а240,0,не указан,NaN,0,р./т,False,69000.0,NaN
3,Арматура А1,NaN,NaN,Число,8.0,NaN,NaN,NaN,NaN,NaN,...,Не указан,не указан,0,не указан,NaN,0,р./т,False,50900.0,NaN
4,Арматура А1,NaN,NaN,Число,8.0,NaN,NaN,NaN,NaN,NaN,...,Сталь,а240,0,не указан,NaN,0,р./т,False,69000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73533,Шина,NaN,NaN,Профиль ГОСТ/СТО,NaN,6.0,Х35,NaN,NaN,NaN,...,Медь,м1,0,не указан,NaN,0,р./т,False,1212000.0,NaN
73534,Шина,NaN,NaN,Профиль ГОСТ/СТО,NaN,8.0,Х50,NaN,NaN,NaN,...,Медь,м1,0,не указан,NaN,0,р./т,False,1212000.0,NaN
73535,Шина,NaN,NaN,Профиль ГОСТ/СТО,NaN,3.0,Х15,NaN,NaN,NaN,...,Медь,м1,0,не указан,NaN,0,р./т,False,1212000.0,NaN
73536,Шина,NaN,NaN,Профиль ГОСТ/СТО,NaN,3.0,Х20,NaN,NaN,NaN,...,Алюминиевый сплав,ад31т,0,не указан,NaN,0,р./т,False,386000.0,NaN
73537,Шина,NaN,NaN,Габарит,12.5,NaN,NaN,NaN,NaN,NaN,...,Медь,м1,0,не указан,NaN,0,р./т,False,1212000.0,NaN